using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Windows.Forms;
using System.Xml;

namespace TestFormDB
{
    public partial class TransferDB : Form
    {
        private TransferDB frm;

        public TransferDB()
        {
            InitializeComponent();
        }

        private void btnnext_Click(object sender, EventArgs e)
        {
            try
            {
                string conString = "Data Source=" + txtserver.Text + ";Database=" + cbbDatabase.Text + ";User Id=" + txtUsername.Text + ";Password=" + txtPassword.Text + "; pooling=false";

                if (!ConnectSQL.CheckConnect(conString))
                {
                    MessageBox.Show("Connect Fail");
                    return;
                }
                else
                {
                    XmlWriterSettings settings = new XmlWriterSettings();
                    settings.Indent = true;

                    XmlWriter writer = XmlWriter.Create(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configDsc.xml", settings);

                    writer.WriteStartDocument();
                    writer.WriteComment("This file is generated by the program.");
                    writer.WriteStartElement("Root");
                    writer.WriteStartElement("LVConfig");
                    writer.WriteElementString("ServerName", txtserver.Text);
                    writer.WriteElementString("UserName", txtUsername.Text);
                    writer.WriteElementString("Password", txtPassword.Text);
                    writer.WriteElementString("Database", cbbDatabase.Text);
                    writer.WriteElementString("ChkSave", chkSavepass.Checked.ToString());
                    writer.WriteEndElement();
                    writer.WriteEndElement();
                    writer.WriteEndDocument();
                    writer.Flush();
                    writer.Close();

                    ListTable frmTbl = new ListTable();
                    Hide();
                    frmTbl.Show();
                }
            }
            catch (Exception es)
            {
                MessageBox.Show("Connect Fail!");
            }
        }

        public List<string> GetDatabaseList()
        {
            try
            {
                List<string> list = new List<string>();

                // Open connection to the database
                string conString = "Data Source=" + txtserver.Text + ";Database=" + cbbDatabase.Text + ";User Id=" + txtUsername.Text + ";Password=" + txtPassword.Text + "; pooling=false";

                using (SqlConnection con = new SqlConnection(conString))
                {
                    con.Open();

                    // Set up a command with the given query and associate
                    // this with the current connection.
                    using (SqlCommand cmd = new SqlCommand("SELECT name from sys.databases", con))
                    {
                        using (IDataReader dr = cmd.ExecuteReader())
                        {
                            while (dr.Read())
                            {
                                list.Add(dr[0].ToString());
                            }
                        }
                    }
                }
                return list;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Connect Fail");
                return null;
            }
        }

        private void TransferDB_Load(object sender, EventArgs e)
        {
            try
            {
                XmlDocument doc = new XmlDocument();
                doc.Load(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configDsc.xml");
                var checkSave = doc.GetElementsByTagName("ChkSave").Item(0).InnerText;
                if (bool.Parse(checkSave) == true)
                {
                    this.txtserver.Text = doc.GetElementsByTagName("ServerName").Item(0).InnerText;
                    this.txtUsername.Text = doc.GetElementsByTagName("UserName").Item(0).InnerText;
                    this.txtPassword.Text = doc.GetElementsByTagName("Password").Item(0).InnerText;                
                    cbbDatabase.Items.Add(doc.GetElementsByTagName("Database").Item(0).InnerText);
                    chkSavepass.Checked = bool.Parse(checkSave);
                    cbbDatabase.SelectedIndex = 0;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Connect Fail");
            }
        }

        private void chkSavepass_CheckedChanged(object sender, EventArgs e)
        {
        }

        private void cbbDatabase_SelectedIndexChanged(object sender, EventArgs e)
        {
        }

        private void rbtnuserWindow_CheckedChanged(object sender, EventArgs e)
        {
            if (rbtnuserWindow.Checked == true)
            {
                txtUsername.Text = "";
                txtPassword.Text = "";
                txtUsername.Enabled = false;
                txtPassword.Enabled = false;
            }
        }

        private void rbtnuserServer_CheckedChanged(object sender, EventArgs e)
        {
            if (rbtnuserServer.Checked == true)
            {
                txtUsername.Text = "";
                txtPassword.Text = "";
                txtUsername.Enabled = true;
                txtPassword.Enabled = true;
            }
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            cbbDatabase.DataSource = GetDatabaseList();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            Form1 frm = new Form1();
            this.Hide();
            frm.Show();
        }

        private void TransferDB_FormClosing(object sender, FormClosingEventArgs e)
        {
            DialogResult tl;
            tl = MessageBox.Show("Bạn có muốn hủy thao tác và quay lại màn hình chính", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (tl == DialogResult.Yes)
            {
                FormMain frm = new FormMain();
                Hide();
                frm.Show();
            }
            else
            {
                e.Cancel = true;
            }
        }
    }
}