using System;
using System.IO;
using System.Windows.Forms;
using System.Xml;

namespace TestFormDB
{
    public partial class FrmConnect : Form
    {
        public FrmConnect()
        {
            InitializeComponent();
        }

        private void btnsaveSrc_Click(object sender, EventArgs e)
        {
            string conString = "Data Source=" + txtserverSrc.Text + ";Database=" + cbbdataSrc.Text + ";User Id=" + txtuserSrc.Text + ";Password=" + txtpassSrc.Text + "; pooling=false";

            if (!ConnectSQL.CheckConnect(conString))
            {
                MessageBox.Show("Lưu thất bại");
                return;
            }
            else
            {
                XmlWriterSettings settings = new XmlWriterSettings();
                settings.Indent = true;

                XmlWriter writer = XmlWriter.Create(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configSrc.xml", settings);

                writer.WriteStartDocument();
                writer.WriteComment("This file is generated by the program.");
                writer.WriteStartElement("Root");
                writer.WriteStartElement("LVConfig");
                writer.WriteElementString("SrcServerName", txtserverSrc.Text);
                writer.WriteElementString("SrcUserName", txtuserSrc.Text);
                writer.WriteElementString("SrcPassword", txtpassSrc.Text);
                writer.WriteElementString("SrcDatabase", cbbdataSrc.Text);
                writer.WriteEndElement();
                writer.WriteEndElement();
                writer.WriteEndDocument();
                writer.Flush();
                writer.Close();
                MessageBox.Show("Lưu thành công");
            }
        }

        private void btnsaveDsc_Click(object sender, EventArgs e)
        {
            try
            {
                string conString = "Data Source=" + txtserverDsc.Text + ";Database=" + cbbDatabaseDsc.Text + ";User Id=" + txtUsernameDsc.Text + ";Password=" + txtPasswordDsc.Text + "; pooling=false";

                if (!ConnectSQL.CheckConnect(conString))
                {
                    MessageBox.Show("Lưu thất bại");
                    return;
                }
                else
                {
                    XmlWriterSettings settings = new XmlWriterSettings();
                    settings.Indent = true;

                    XmlWriter writer = XmlWriter.Create(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configDsc.xml", settings);

                    writer.WriteStartDocument();
                    writer.WriteComment("This file is generated by the program.");
                    writer.WriteStartElement("Root");
                    writer.WriteStartElement("LVConfig");
                    writer.WriteElementString("ServerName", txtserverDsc.Text);
                    writer.WriteElementString("UserName", txtUsernameDsc.Text);
                    writer.WriteElementString("Password", txtPasswordDsc.Text);
                    writer.WriteElementString("Database", cbbDatabaseDsc.Text);
                    writer.WriteEndElement();
                    writer.WriteEndDocument();
                    writer.Flush();
                    writer.Close();

                    MessageBox.Show("Lưu thành công");
                }
            }
            catch (Exception es)
            {
                MessageBox.Show("Lưu thất bại");
            }
        }

        private void FrmConnect_Load(object sender, EventArgs e)
        {
            try
            {
                XmlDocument docDsc = new XmlDocument();
                docDsc.Load(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configDsc.xml");

                this.txtserverDsc.Text = docDsc.GetElementsByTagName("ServerName").Item(0).InnerText;
                this.txtUsernameDsc.Text = docDsc.GetElementsByTagName("UserName").Item(0).InnerText;
                this.txtPasswordDsc.Text = docDsc.GetElementsByTagName("Password").Item(0).InnerText;
                cbbDatabaseDsc.Items.Add(docDsc.GetElementsByTagName("Database").Item(0).InnerText);
                cbbDatabaseDsc.SelectedIndex = 0;

                XmlDocument docSrc = new XmlDocument();
                docSrc.Load(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) + "\\configSrc.xml");

                this.txtserverSrc.Text = docSrc.GetElementsByTagName("SrcServerName").Item(0).InnerText;
                this.txtuserSrc.Text = docSrc.GetElementsByTagName("SrcUserName").Item(0).InnerText;
                this.txtpassSrc.Text = docSrc.GetElementsByTagName("SrcPassword").Item(0).InnerText;
                cbbdataSrc.Items.Add(docSrc.GetElementsByTagName("SrcDatabase").Item(0).InnerText);
                cbbdataSrc.SelectedIndex = 0;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Connect Fail");
            }
        }

        private void rdbwindowSrc_CheckedChanged(object sender, EventArgs e)
        {
            if (rdbwindowSrc.Checked == true)
            {
                txtuserSrc.Text = "";
                txtpassSrc.Text = "";
                txtuserSrc.Enabled = false;
                txtpassSrc.Enabled = false;
            }
            else
            {
                txtuserSrc.Enabled = true;
                txtpassSrc.Enabled = true;
            }
        }

        private void rbtnuserWindowDsc_CheckedChanged(object sender, EventArgs e)
        {
            if (rbtnuserWindowDsc.Checked == true)
            {
                txtUsernameDsc.Text = "";
                txtPasswordDsc.Text = "";
                txtUsernameDsc.Enabled = false;
                txtPasswordDsc.Enabled = false;
            }
            else
            {
                txtPasswordDsc.Enabled = true;
                txtUsernameDsc.Enabled = true;
            }
        }

        private void btnRefreshDsc_Click(object sender, EventArgs e)
        {
            cbbDatabaseDsc.DataSource = GetDatabase.GetDatabaseList(txtserverDsc.Text, null, txtUsernameDsc.Text, txtPasswordDsc.Text);
        }

        private void btnRefreshSrc_Click(object sender, EventArgs e)
        {
            cbbdataSrc.DataSource = GetDatabase.GetDatabaseList(txtserverSrc.Text, null, txtuserSrc.Text, txtpassSrc.Text);
        }
    }
}